services:
  classifier-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - dnd

networks:
  dnd:
    external: true
    name: dnd
