defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
   run:
     dir: .
   job:
       chdir: false

wandb:
  project: dnd_classifier_training         # Replace with your wandb project name

data:
  dir: "data"
  file_name: "train.csv"
  data_path: "data/dataset_isrelated.json"      # Path to your JSON data file
  eval_split: 0.2             # Fraction of data to use for evaluation (e.g., 20%)
  seed: 42                    # Seed for reproducible splits

model:
  num_labels: 2               # Number of labels for classification
  model_name_or_path: "intfloat/multilingual-e5-large-instruct"

tokenizer:
  max_length: 512             # Maximum sequence length

training:
  output_dir: "./results"
  num_train_epochs: 1
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  gradient_accumulation_steps: 2
  evaluation_strategy: "steps"    # Can be "steps" or "epoch"
  eval_steps: 50                 # Number of steps between evaluations (if using "steps")
  logging_dir: "./logs"
  run_name: "multilingual-e5-large-instruct-classifier"
